version: 0.0 ##version
os: linux  ## OS type
files:
  - source: /  ##source file
    destination: /var/www/html/ ## destination directory
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 120
      runas: root
    - location: scripts/start_server
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 120
      runas: root

