version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code
      - echo Running unit tests
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  overwrite: true

